// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: dfu-cc.proto

package dfu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definition of enums and types
type OpCode int32

const (
	OpCode_RESET OpCode = 0
	OpCode_INIT  OpCode = 1
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "RESET",
		1: "INIT",
	}
	OpCode_value = map[string]int32{
		"RESET": 0,
		"INIT":  1,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_dfu_cc_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_dfu_cc_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OpCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OpCode(num)
	return nil
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{0}
}

type FwType int32

const (
	FwType_APPLICATION           FwType = 0 // default, compatible with proto3
	FwType_SOFTDEVICE            FwType = 1
	FwType_BOOTLOADER            FwType = 2
	FwType_SOFTDEVICE_BOOTLOADER FwType = 3
	FwType_EXTERNAL_APPLICATION  FwType = 4
)

// Enum value maps for FwType.
var (
	FwType_name = map[int32]string{
		0: "APPLICATION",
		1: "SOFTDEVICE",
		2: "BOOTLOADER",
		3: "SOFTDEVICE_BOOTLOADER",
		4: "EXTERNAL_APPLICATION",
	}
	FwType_value = map[string]int32{
		"APPLICATION":           0,
		"SOFTDEVICE":            1,
		"BOOTLOADER":            2,
		"SOFTDEVICE_BOOTLOADER": 3,
		"EXTERNAL_APPLICATION":  4,
	}
)

func (x FwType) Enum() *FwType {
	p := new(FwType)
	*p = x
	return p
}

func (x FwType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FwType) Descriptor() protoreflect.EnumDescriptor {
	return file_dfu_cc_proto_enumTypes[1].Descriptor()
}

func (FwType) Type() protoreflect.EnumType {
	return &file_dfu_cc_proto_enumTypes[1]
}

func (x FwType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FwType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FwType(num)
	return nil
}

// Deprecated: Use FwType.Descriptor instead.
func (FwType) EnumDescriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{1}
}

type HashType int32

const (
	HashType_NO_HASH HashType = 0
	HashType_CRC     HashType = 1
	HashType_SHA128  HashType = 2
	HashType_SHA256  HashType = 3
	HashType_SHA512  HashType = 4
)

// Enum value maps for HashType.
var (
	HashType_name = map[int32]string{
		0: "NO_HASH",
		1: "CRC",
		2: "SHA128",
		3: "SHA256",
		4: "SHA512",
	}
	HashType_value = map[string]int32{
		"NO_HASH": 0,
		"CRC":     1,
		"SHA128":  2,
		"SHA256":  3,
		"SHA512":  4,
	}
)

func (x HashType) Enum() *HashType {
	p := new(HashType)
	*p = x
	return p
}

func (x HashType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashType) Descriptor() protoreflect.EnumDescriptor {
	return file_dfu_cc_proto_enumTypes[2].Descriptor()
}

func (HashType) Type() protoreflect.EnumType {
	return &file_dfu_cc_proto_enumTypes[2]
}

func (x HashType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HashType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HashType(num)
	return nil
}

// Deprecated: Use HashType.Descriptor instead.
func (HashType) EnumDescriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{2}
}

type ValidationType int32

const (
	ValidationType_NO_VALIDATION              ValidationType = 0
	ValidationType_VALIDATE_GENERATED_CRC     ValidationType = 1
	ValidationType_VALIDATE_SHA256            ValidationType = 2
	ValidationType_VALIDATE_ECDSA_P256_SHA256 ValidationType = 3
)

// Enum value maps for ValidationType.
var (
	ValidationType_name = map[int32]string{
		0: "NO_VALIDATION",
		1: "VALIDATE_GENERATED_CRC",
		2: "VALIDATE_SHA256",
		3: "VALIDATE_ECDSA_P256_SHA256",
	}
	ValidationType_value = map[string]int32{
		"NO_VALIDATION":              0,
		"VALIDATE_GENERATED_CRC":     1,
		"VALIDATE_SHA256":            2,
		"VALIDATE_ECDSA_P256_SHA256": 3,
	}
)

func (x ValidationType) Enum() *ValidationType {
	p := new(ValidationType)
	*p = x
	return p
}

func (x ValidationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationType) Descriptor() protoreflect.EnumDescriptor {
	return file_dfu_cc_proto_enumTypes[3].Descriptor()
}

func (ValidationType) Type() protoreflect.EnumType {
	return &file_dfu_cc_proto_enumTypes[3]
}

func (x ValidationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ValidationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ValidationType(num)
	return nil
}

// Deprecated: Use ValidationType.Descriptor instead.
func (ValidationType) EnumDescriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{3}
}

// Signed command types
type SignatureType int32

const (
	SignatureType_ECDSA_P256_SHA256 SignatureType = 0
	SignatureType_ED25519           SignatureType = 1
)

// Enum value maps for SignatureType.
var (
	SignatureType_name = map[int32]string{
		0: "ECDSA_P256_SHA256",
		1: "ED25519",
	}
	SignatureType_value = map[string]int32{
		"ECDSA_P256_SHA256": 0,
		"ED25519":           1,
	}
)

func (x SignatureType) Enum() *SignatureType {
	p := new(SignatureType)
	*p = x
	return p
}

func (x SignatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_dfu_cc_proto_enumTypes[4].Descriptor()
}

func (SignatureType) Type() protoreflect.EnumType {
	return &file_dfu_cc_proto_enumTypes[4]
}

func (x SignatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SignatureType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SignatureType(num)
	return nil
}

// Deprecated: Use SignatureType.Descriptor instead.
func (SignatureType) EnumDescriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{4}
}

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashType *HashType `protobuf:"varint,1,req,name=hash_type,json=hashType,enum=dfu.HashType" json:"hash_type,omitempty"`
	Hash     []byte    `protobuf:"bytes,2,req,name=hash" json:"hash,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{0}
}

func (x *Hash) GetHashType() HashType {
	if x != nil && x.HashType != nil {
		return *x.HashType
	}
	return HashType_NO_HASH
}

func (x *Hash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BootValidation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *ValidationType `protobuf:"varint,1,req,name=type,enum=dfu.ValidationType" json:"type,omitempty"`
	Bytes []byte          `protobuf:"bytes,2,req,name=bytes" json:"bytes,omitempty"`
}

func (x *BootValidation) Reset() {
	*x = BootValidation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootValidation) ProtoMessage() {}

func (x *BootValidation) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootValidation.ProtoReflect.Descriptor instead.
func (*BootValidation) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{1}
}

func (x *BootValidation) GetType() ValidationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ValidationType_NO_VALIDATION
}

func (x *BootValidation) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// Commands data
type InitCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FwVersion      *uint32           `protobuf:"varint,1,opt,name=fw_version,json=fwVersion" json:"fw_version,omitempty"`
	HwVersion      *uint32           `protobuf:"varint,2,opt,name=hw_version,json=hwVersion" json:"hw_version,omitempty"`
	SdReq          []uint32          `protobuf:"varint,3,rep,packed,name=sd_req,json=sdReq" json:"sd_req,omitempty"` // packed option is default in proto3
	Type           *FwType           `protobuf:"varint,4,opt,name=type,enum=dfu.FwType" json:"type,omitempty"`
	SdSize         *uint32           `protobuf:"varint,5,opt,name=sd_size,json=sdSize" json:"sd_size,omitempty"`
	BlSize         *uint32           `protobuf:"varint,6,opt,name=bl_size,json=blSize" json:"bl_size,omitempty"`
	AppSize        *uint32           `protobuf:"varint,7,opt,name=app_size,json=appSize" json:"app_size,omitempty"`
	Hash           *Hash             `protobuf:"bytes,8,opt,name=hash" json:"hash,omitempty"`
	IsDebug        *bool             `protobuf:"varint,9,opt,name=is_debug,json=isDebug,def=0" json:"is_debug,omitempty"`
	BootValidation []*BootValidation `protobuf:"bytes,10,rep,name=boot_validation,json=bootValidation" json:"boot_validation,omitempty"`
}

// Default values for InitCommand fields.
const (
	Default_InitCommand_IsDebug = bool(false)
)

func (x *InitCommand) Reset() {
	*x = InitCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCommand) ProtoMessage() {}

func (x *InitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCommand.ProtoReflect.Descriptor instead.
func (*InitCommand) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{2}
}

func (x *InitCommand) GetFwVersion() uint32 {
	if x != nil && x.FwVersion != nil {
		return *x.FwVersion
	}
	return 0
}

func (x *InitCommand) GetHwVersion() uint32 {
	if x != nil && x.HwVersion != nil {
		return *x.HwVersion
	}
	return 0
}

func (x *InitCommand) GetSdReq() []uint32 {
	if x != nil {
		return x.SdReq
	}
	return nil
}

func (x *InitCommand) GetType() FwType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return FwType_APPLICATION
}

func (x *InitCommand) GetSdSize() uint32 {
	if x != nil && x.SdSize != nil {
		return *x.SdSize
	}
	return 0
}

func (x *InitCommand) GetBlSize() uint32 {
	if x != nil && x.BlSize != nil {
		return *x.BlSize
	}
	return 0
}

func (x *InitCommand) GetAppSize() uint32 {
	if x != nil && x.AppSize != nil {
		return *x.AppSize
	}
	return 0
}

func (x *InitCommand) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *InitCommand) GetIsDebug() bool {
	if x != nil && x.IsDebug != nil {
		return *x.IsDebug
	}
	return Default_InitCommand_IsDebug
}

func (x *InitCommand) GetBootValidation() []*BootValidation {
	if x != nil {
		return x.BootValidation
	}
	return nil
}

type ResetCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout *uint32 `protobuf:"varint,1,req,name=timeout" json:"timeout,omitempty"`
}

func (x *ResetCommand) Reset() {
	*x = ResetCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCommand) ProtoMessage() {}

func (x *ResetCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCommand.ProtoReflect.Descriptor instead.
func (*ResetCommand) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{3}
}

func (x *ResetCommand) GetTimeout() uint32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

// Command type
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpCode *OpCode       `protobuf:"varint,1,opt,name=op_code,json=opCode,enum=dfu.OpCode" json:"op_code,omitempty"`
	Init   *InitCommand  `protobuf:"bytes,2,opt,name=init" json:"init,omitempty"`
	Reset_ *ResetCommand `protobuf:"bytes,3,opt,name=reset" json:"reset,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetOpCode() OpCode {
	if x != nil && x.OpCode != nil {
		return *x.OpCode
	}
	return OpCode_RESET
}

func (x *Command) GetInit() *InitCommand {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *Command) GetReset_() *ResetCommand {
	if x != nil {
		return x.Reset_
	}
	return nil
}

type SignedCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command       *Command       `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	SignatureType *SignatureType `protobuf:"varint,2,req,name=signature_type,json=signatureType,enum=dfu.SignatureType" json:"signature_type,omitempty"`
	Signature     []byte         `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
}

func (x *SignedCommand) Reset() {
	*x = SignedCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCommand) ProtoMessage() {}

func (x *SignedCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCommand.ProtoReflect.Descriptor instead.
func (*SignedCommand) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{5}
}

func (x *SignedCommand) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SignedCommand) GetSignatureType() SignatureType {
	if x != nil && x.SignatureType != nil {
		return *x.SignatureType
	}
	return SignatureType_ECDSA_P256_SHA256
}

func (x *SignedCommand) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Parent packet type
type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command       *Command       `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	SignedCommand *SignedCommand `protobuf:"bytes,2,opt,name=signed_command,json=signedCommand" json:"signed_command,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfu_cc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_dfu_cc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_dfu_cc_proto_rawDescGZIP(), []int{6}
}

func (x *Packet) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Packet) GetSignedCommand() *SignedCommand {
	if x != nil {
		return x.SignedCommand
	}
	return nil
}

var File_dfu_cc_proto protoreflect.FileDescriptor

var file_dfu_cc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x66, 0x75, 0x2d, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x64, 0x66, 0x75, 0x22, 0x46, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x09, 0x68,
	0x61, 0x73, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x64, 0x66, 0x75, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x4f, 0x0a, 0x0e, 0x42,
	0x6f, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x64, 0x66,
	0x75, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0xd3, 0x02, 0x0a,
	0x0b, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x66, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x68, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x06, 0x73, 0x64,
	0x5f, 0x72, 0x65, 0x71, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x05,
	0x73, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x64, 0x66, 0x75, 0x2e, 0x46, 0x77, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x64, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x62, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x62, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x70, 0x70, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x64, 0x66, 0x75, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x20, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x07, 0x69, 0x73, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x12, 0x3c, 0x0a, 0x0f, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x64, 0x66, 0x75, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x7e, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x64, 0x66, 0x75, 0x2e, 0x4f,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x66,
	0x75, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x04, 0x69,
	0x6e, 0x69, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22, 0x90, 0x01, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x26,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x64, 0x66, 0x75, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x39, 0x0a, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x64, 0x66, 0x75, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x6b, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x66, 0x75,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x39, 0x0a, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x66, 0x75, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x0d, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2a, 0x1d, 0x0a, 0x06,
	0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x53, 0x45, 0x54, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x01, 0x2a, 0x6e, 0x0a, 0x06, 0x46,
	0x77, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4f, 0x46, 0x54, 0x44, 0x45,
	0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x4f, 0x4f, 0x54, 0x4c, 0x4f,
	0x41, 0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x4f, 0x46, 0x54, 0x44, 0x45,
	0x56, 0x49, 0x43, 0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x54, 0x4c, 0x4f, 0x41, 0x44, 0x45, 0x52, 0x10,
	0x03, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x41, 0x50,
	0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x2a, 0x44, 0x0a, 0x08, 0x48,
	0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x48, 0x41,
	0x53, 0x48, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x52, 0x43, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x48, 0x41, 0x31, 0x32, 0x38, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41,
	0x32, 0x35, 0x36, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x48, 0x41, 0x35, 0x31, 0x32, 0x10,
	0x04, 0x2a, 0x74, 0x0a, 0x0e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x43, 0x52, 0x43,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53,
	0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x41, 0x54, 0x45, 0x5f, 0x45, 0x43, 0x44, 0x53, 0x41, 0x5f, 0x50, 0x32, 0x35, 0x36, 0x5f, 0x53,
	0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x03, 0x2a, 0x33, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x43, 0x44, 0x53,
	0x41, 0x5f, 0x50, 0x32, 0x35, 0x36, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x44, 0x32, 0x35, 0x35, 0x31, 0x39, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x6e, 0x72, 0x66, 0x2f, 0x64, 0x66, 0x75,
}

var (
	file_dfu_cc_proto_rawDescOnce sync.Once
	file_dfu_cc_proto_rawDescData = file_dfu_cc_proto_rawDesc
)

func file_dfu_cc_proto_rawDescGZIP() []byte {
	file_dfu_cc_proto_rawDescOnce.Do(func() {
		file_dfu_cc_proto_rawDescData = protoimpl.X.CompressGZIP(file_dfu_cc_proto_rawDescData)
	})
	return file_dfu_cc_proto_rawDescData
}

var file_dfu_cc_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_dfu_cc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dfu_cc_proto_goTypes = []interface{}{
	(OpCode)(0),            // 0: dfu.OpCode
	(FwType)(0),            // 1: dfu.FwType
	(HashType)(0),          // 2: dfu.HashType
	(ValidationType)(0),    // 3: dfu.ValidationType
	(SignatureType)(0),     // 4: dfu.SignatureType
	(*Hash)(nil),           // 5: dfu.Hash
	(*BootValidation)(nil), // 6: dfu.BootValidation
	(*InitCommand)(nil),    // 7: dfu.InitCommand
	(*ResetCommand)(nil),   // 8: dfu.ResetCommand
	(*Command)(nil),        // 9: dfu.Command
	(*SignedCommand)(nil),  // 10: dfu.SignedCommand
	(*Packet)(nil),         // 11: dfu.Packet
}
var file_dfu_cc_proto_depIdxs = []int32{
	2,  // 0: dfu.Hash.hash_type:type_name -> dfu.HashType
	3,  // 1: dfu.BootValidation.type:type_name -> dfu.ValidationType
	1,  // 2: dfu.InitCommand.type:type_name -> dfu.FwType
	5,  // 3: dfu.InitCommand.hash:type_name -> dfu.Hash
	6,  // 4: dfu.InitCommand.boot_validation:type_name -> dfu.BootValidation
	0,  // 5: dfu.Command.op_code:type_name -> dfu.OpCode
	7,  // 6: dfu.Command.init:type_name -> dfu.InitCommand
	8,  // 7: dfu.Command.reset:type_name -> dfu.ResetCommand
	9,  // 8: dfu.SignedCommand.command:type_name -> dfu.Command
	4,  // 9: dfu.SignedCommand.signature_type:type_name -> dfu.SignatureType
	9,  // 10: dfu.Packet.command:type_name -> dfu.Command
	10, // 11: dfu.Packet.signed_command:type_name -> dfu.SignedCommand
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_dfu_cc_proto_init() }
func file_dfu_cc_proto_init() {
	if File_dfu_cc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dfu_cc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfu_cc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootValidation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfu_cc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfu_cc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfu_cc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfu_cc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfu_cc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dfu_cc_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dfu_cc_proto_goTypes,
		DependencyIndexes: file_dfu_cc_proto_depIdxs,
		EnumInfos:         file_dfu_cc_proto_enumTypes,
		MessageInfos:      file_dfu_cc_proto_msgTypes,
	}.Build()
	File_dfu_cc_proto = out.File
	file_dfu_cc_proto_rawDesc = nil
	file_dfu_cc_proto_goTypes = nil
	file_dfu_cc_proto_depIdxs = nil
}
